### ISSUE TITLE
5.2 to 6.1 Migration issue 

### ISSUE THREAD

**Issue by jubaExpressDev** [regulaforensics/FaceSDK-Android#15]
implementation("com.regula.face:api:6.1.3021@aar") {
        isTransitive = true
    }
    implementation("com.regula.face.core:basic:6.1.407@aar")
    
 also Added
    aaptOptions {
        noCompress("Regula/faceSdkResource.dat")
    }

Error -> **RESOURCE_DAT_ABSENT** screenshot attached below
![Screenshot (1)](https://github.com/regulaforensics/FaceSDK-Android/assets/109176875/0ed7bedf-e14a-4436-911f-b6912942c744)

**Comment by syakimchik** [comment]
Hello @jubaExpressDev,

Please, reinstall your app again.
But in the 6.2 version it's not require to add "**noCompress("Regula/faceSdkResource.dat")**"
