### ISSUE TITLE
[BR] Not working in Android 14 is there any update ?

### ISSUE THREAD

**Issue by ranashivam0208** [regulaforensics/FaceSDK-Android#16]
Fatal Exception: java.lang.RuntimeException
Unable to resume activity {com.sevensalesVfourZeroOne/com.regula.facesdk.FaceCaptureActivity}: java.lang.SecurityException: com.sevensalesVfourZeroOne: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

**Comment by DmitrySmolyakov** [comment]
Hello, this issue fixed starting from 5.2.2825 version
